In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
input_data = np.array([[5.1, -2.9, 3.3],
                       [-1.2, 7.8, -6.1],
                       [3.9, 0.4, 2.1],
                       [7.3, -9.9, -4.5]])

In [3]:
input_data

array([[ 5.1, -2.9,  3.3],
       [-1.2,  7.8, -6.1],
       [ 3.9,  0.4,  2.1],
       [ 7.3, -9.9, -4.5]])

### 2.3.1 二値化

In [7]:
# thresholdの値を境に二値化
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("Binarized data:\n", data_binarized)

Binarized data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


### 2.3.2 平均値を引く

In [10]:
print("BEFORE:")
print("Mean =", input_data.mean(axis=0))         # 平均値
print("Std deviation =", input_data.std(axis=0)) # 標準偏差


BEFORE:
Mean = [ 3.775 -1.15  -1.3  ]
Std deviation = [3.12039661 6.36651396 4.0620192 ]


scale()を使うと、平均値を引いてから、標準偏差が１になるようにスケーリングを行います。

In [11]:
data_scaled = preprocessing.scale(input_data)
print("AFTER:")
print("Mean =", data_scaled.mean(axis=0))         # 平均値
print("Std deviation =", data_scaled.std(axis=0)) # 標準偏差

AFTER:
Mean = [1.11022302e-16 0.00000000e+00 2.77555756e-17]
Std deviation = [1. 1. 1.]


### 2.3.3 スケーリング

### 2.3.4 正規化